CREATE DATABASE IF NOT EXISTS projeto_github;
USE projeto_github;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    senha VARCHAR(255) NOT NULL
);